image: denoland/deno:1.17.2

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - deno_dir

typecheck:
  rules:
    - if: '$CI_COMMIT_TAG == null'
  script:
    - deno cache src/mod.ts

compile:
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apt-get update
    - apt-get install -y unzip
    - ./compile.sh
  artifacts:
    paths:
      - dist/*
